[package]
name = "wacom-gestures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# wacom-sys = "0.1.0"

[build-dependencies]
bindgen = "0.66.1"